# Generated by Django 6.0 on 2025-12-25 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cas_number', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('MT', 'MT'), ('Litre', 'Litre')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.chemicalproduct')),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
